version: '3'

services:
  'graphql-app':
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    container_name: 'graphql-app'
    command: ./node_modules/.bin/react-scripts start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src
    depends_on:
      - graphql-server

  'graphql-server':
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    container_name: 'graphql-server'
    # This service will not start until either the mongodb service is available OR thirty seconds have elapsed
    command: sh -c './scripts/wait-for.sh --timeout=30 mongodb:27017 && ./node_modules/.bin/nodemon -e js,json,graphql'
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "graphql-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # If you want to persist MongoDB data after a container has been stopped/deleted, uncomment the volumes section
    # volumes:
    #   - ./server/.docker/mongodb/data/db:/data/db
    ports:
      - "27017:27017"
